spring:
  application:
    name: SPRING-CLOUD-CONFIG #注册进eureka服务器的名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kejianming/springcloud-learning.git
          search-paths: #搜索目录
            - springcloud-learning
          username: kejianming
          password: 961004@abcd
      label: main

eureka:
  client:
    service-url:
      #入驻地址
      #单机版
      #defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com/eureka